/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devmodule4;

import database.DatabaseInitService;
import org.junit.jupiter.api.Test;

class DatabaseInitServiceTest {
    @Test void appHasAGreeting() {
        DatabaseInitService classUnderTest = new DatabaseInitService();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
